# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Movie.destroy_all

Movie.create(title: "San Andreas",release_date: Date.new(2015,5,28),rating: "M",director: "Brad Peyton",cast: "Dwayne Johnson, Carla Gugino, Alexandra Daddario, Ioan Gruffudd, Archie Panjabi, Paul Giamatti, Kylie Minogue",duration: 114,score: 2,demographic_score: 5.5,imdbid: "tt2126355",review: "If you’ve seen any disaster flick made in the last 2 decades; be it Volcano, The Day After Tomorrow or 2012 - you know what you’re buying a ticket for. And we all know these kinds of flicks aren’t made to please critics; so don’t read on if you’re looking for ‘Happy Pete’ here. Right, so stop me if you’ve heard any of these ideas before … the earth &/or skyscrapers collapse around a major character but doesn’t harm them; the hand of a major character about to fall, drown etc. will always be grabbed at the last possible moment; or the vehicle driven by a major character somehow always scores a direct path to safety even when every other car somehow doesn’t … Or is it just me?? Aside from the total ignorance of real science (which granted most action flicks do), whist watching San Andreas, I could really only see 2 notes that were given by the studio exec’s: 1. get Johnson in all his sincere, muscle-bound glory onscreen for every second possible & 2. for the Wardrobe Dept - make sure the 2 chesty female leads (Gugino - Johnson’s soon-to-be-ex-wife & Daddario - his estranged daughter) are dressed exclusively in t-shirts that are clearly 6 sizes too small!! To be honest - I love Johnson. Like many other action stars, he delivers more often than not with a certain kind of flick. But unfortunately, not even The Rock can rescue SA from its total stupidity. Don’t get me wrong - most action films are always at their very core, escapist nonsense. But they can still be well made. I mean the people behind the Fast & Furious franchise know their flicks are ridiculous, & we the audience know that they know it. So we’re all in it together. But SA is just a cliché-ridden, cheese-fest!! After the San Andreas Fault goes nuts & triggers a massive earthquake in LA, Johnson’s search & rescue pilot (who’s naturally also ex-special forces) has to firstly save his estranged wife, before they … (reviewer sniggers to himself) … team up to save their only daughter from the 2nd wave of the tremor up the coast in San Francisco. But surprise, surprise; just when they think everything’s okay, it turns out Mother Nature’s just getting started!! The majority of the movie was shot in QLD - Movie World, Brisbane CBD & the Lockyer Valley. Unfortunately though, this is probably not a film we Aussies want to take too much credit for. The visuals are average at best, the script is appalling, & not even Johnson’s hulking biceps & likeable personality can save the world from this crap-fest. Save the world? No, just save your $$.",trailer_link: "23VflsU3kZE",poster_link: "http://ia.media-imdb.com/images/M/MV5BNDQ3OTAzMDI3MV5BMl5BanBnXkFtZTgwNTUzMTQ3NDE@._V1_SX300.jpg")
